//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FINAL_NETWORK
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AspDataEntities : DbContext
    {
        public AspDataEntities()
            : base("name=AspDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<AspTaple> AspTaples { get; set; }
        public virtual DbSet<FATORA> FATORAs { get; set; }
        public virtual DbSet<favort> favorts { get; set; }
        public virtual DbSet<GAME> GAMEs { get; set; }
    }
}
